/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.4
 * Generated at: 2016-07-19 02:31:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class studentList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/jsp/admin/student/../include/tail.jsp", Long.valueOf(1462930713634L));
    _jspx_dependants.put("/WEB-INF/jsp/admin/student/../include/left.jsp", Long.valueOf(1465269926187L));
    _jspx_dependants.put("/WEB-INF/jsp/admin/student/../../common/head.jsp", Long.valueOf(1462930713642L));
    _jspx_dependants.put("/WEB-INF/jsp/admin/student/../include/top.jsp", Long.valueOf(1462930713634L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1395814099278L));
    _jspx_dependants.put("jar:file:/D:/ProgrameFiles/MagicalCoder-all/MagicalCoder/windows64bit/project/apache-tomcat-8.5.4/../youyamvc/youyamvc-web/target/youyamvc-web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/D:/ProgrameFiles/MagicalCoder-all/MagicalCoder/windows64bit/project/apache-tomcat-8.5.4/../youyamvc/youyamvc-web/target/youyamvc-web/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/jsp/admin/student/../include/head.jsp", Long.valueOf(1462930713633L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CTX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<meta charset=\"UTF-8\">");
      out.write("\r\n");
      out.write("    <title>AdminLTE | Dashboard</title>\r\n");
      out.write("    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap 3.0.2 -->\r\n");
      out.write("<link href=\"assets/admin/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- font Awesome -->\r\n");
      out.write("<link href=\"assets/admin/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Ionicons -->\r\n");
      out.write("<link href=\"assets/admin/css/ionicons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Morris chart -->\r\n");
      out.write("<link href=\"assets/admin/css/morris/morris.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- jvectormap -->\r\n");
      out.write("<link href=\"assets/admin/css/jvectormap/jquery-jvectormap-1.2.2.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- bootstrap wysihtml5 - text editor -->\r\n");
      out.write("<link href=\"assets/admin/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Theme style -->\r\n");
      out.write("<link href=\"assets/admin/css/AdminLTE.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"assets/admin/css/datatables/dataTables.bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"assets/admin/js/jquery/1.8.2/jquery-min-1.8.2.js\"></script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- Theme style -->\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"assets/admin/js/AdminLTE/html5shiv-3.7.0.js\"></script>\r\n");
      out.write("<script src=\"assets/admin/js/AdminLTE/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"assets/admin/js/json.js\"></script>\r\n");
      out.write("<script  type=\"text/javascript\">\r\n");
      out.write("    var CTX = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CTX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"skin-blue\">\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<a href=\"http://www.magicalcoder.com\" class=\"logo\">\r\n");
      out.write("    <!-- Add the class icon to your logo image or logo icon to add the margining -->\r\n");
      out.write("    MagicalCoder\r\n");
      out.write("</a>\r\n");
      out.write("<!-- Header Navbar: style can be found in header.less -->\r\n");
      out.write("<nav class=\"navbar navbar-static-top\" role=\"navigation\">\r\n");
      out.write("    <!-- Sidebar toggle button-->\r\n");
      out.write("    <a href=\"#\" class=\"navbar-btn sidebar-toggle\" data-toggle=\"offcanvas\" role=\"button\">\r\n");
      out.write("        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"navbar-right\">\r\n");
      out.write("        <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <!-- User Account: style can be found in dropdown.less -->\r\n");
      out.write("            <li class=\"dropdown user user-menu\" id=\"loginOut\">\r\n");
      out.write("                <a href=\"admin/loginOut\" class=\"dropdown-toggle\">\r\n");
      out.write("                    <i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("                    <span>退出登录</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<script src=\"assets/admin/app/top.js\" type=\"text/javascript\"></script>");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"wrapper row-offcanvas row-offcanvas-left\">\r\n");
      out.write("    <aside class=\"left-side sidebar-offcanvas\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<!-- sidebar: style can be found in sidebar.less -->\r\n");
      out.write("<section class=\"sidebar\">\r\n");
      out.write("    <!-- Sidebar user panel -->\r\n");
      out.write("    <div class=\"user-panel\">\r\n");
      out.write("        <div class=\"pull-left image\">\r\n");
      out.write("            <img src=\"assets/admin/img/avatar3.png\" class=\"img-circle\" alt=\"User Image\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"pull-left info\">\r\n");
      out.write("            <p id=\"magicalCoderUserName\"></p>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-circle text-success\"></i> 在线</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 配置好a的id（按层定 ）即可 利用了cookie 自动记录当前点击的id  -->\r\n");
      out.write("    <ul class=\"sidebar-menu\"  id=\"leftNavigate\">\r\n");
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("</section>\r\n");
      out.write("<script src=\"assets/admin/app/left.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("    </aside>\r\n");
      out.write("    <aside class=\"right-side\">\r\n");
      out.write("        <section class=\"content-header\">\r\n");
      out.write("            <h1>\r\n");
      out.write("                学生列表 \r\n");
      out.write("                <a class=\"btn btn-app\" href=\"admin/student/detail\"><i class=\"fa fa-edit\"></i>新增</a>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-dashboard\"></i> 首页</a></li>\r\n");
      out.write("                <li><a href=\"#\">li</a></li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Main content -->\r\n");
      out.write("        <section class=\"content\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xs-12\">\r\n");
      out.write("                    <div class=\"box\">\r\n");
      out.write("                        <div class=\"box-header\">\r\n");
      out.write("                            <div class=\"box-tools\">\r\n");
      out.write("                                <div class=\"form\">\r\n");
      out.write("                                    <div class=\"box-body\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("\r                                             <div class=\"col-xs-2\">\r\n");
      out.write("                                                 <div class=\"form-group\">\r\n");
      out.write("                                                     <label for=\"nameFirst\">学生名称 (=)</label>\r\n");
      out.write("                                                     <input type=\"text\" class=\"form-control\"\r\n");
      out.write("                                                      value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ nameFirst }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                                                                                    id=\"nameFirst\" name=\"nameFirst\">\r\n");
      out.write("                                                 </div>\r\n");
      out.write("                                             </div>\r\n");
      out.write("                                              <div class=\"col-xs-2\">\r\n");
      out.write("                                                 <div class=\"form-group\">\r\n");
      out.write("                                             <label for=\"classIdFirst\">所属班级</label>\r\n");
      out.write("                                            <input type=\"hidden\" id=\"classIdFirst\"\r\n");
      out.write("                                                   name=\"classIdFirst\"\r\n");
      out.write("                                                   value=\"\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"classIdFirstSearch\"\r\n");
      out.write("                                                  name=\"classIdFirstSearch\"  placeholder=\"请输入关键词查询班级\"\r\n");
      out.write("                                                         value=\"\">\r\n");
      out.write("                                                 </div>\r\n");
      out.write("                                             </div>                                             <div class=\"col-xs-2\">\r\n");
      out.write("                                                 <div class=\"form-group\">\r\n");
      out.write("                                                 <label for=\"sexFirst\">性别</label>\r\n");
      out.write("                                                     <select class=\"form-control\" id=\"sexFirst\" name=\"sexFirst\">\r\n");
      out.write("                                                                 <option value=\"\">全部</option>\r\n");
      out.write("                                                                 <option value=\"0\"\r\n");
      out.write("                                                                     ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                                                  >类型一\r\n");
      out.write("                                                                 </option>\r\n");
      out.write("                                                                 <option value=\"1\"\r\n");
      out.write("                                                                     ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                                                  >类型二\r\n");
      out.write("                                                                 </option>\r\n");
      out.write("                                                     </select>\r\n");
      out.write("                                                 </div>\r\n");
      out.write("                                             </div>                                              <div class=\"col-xs-2\">\r\n");
      out.write("                                                 <div class=\"form-group\">\r\n");
      out.write("                                             <label for=\"adminUserIdFirst\">管理员</label>\r\n");
      out.write("                                            <input type=\"hidden\" id=\"adminUserIdFirst\"\r\n");
      out.write("                                                   name=\"adminUserIdFirst\"\r\n");
      out.write("                                                   value=\"\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"adminUserIdFirstSearch\"\r\n");
      out.write("                                                  name=\"adminUserIdFirstSearch\"  placeholder=\"请输入关键词查询管理员表\"\r\n");
      out.write("                                                         value=\"\">\r\n");
      out.write("                                                 </div>\r\n");
      out.write("                                             </div>                                                <div class=\"col-xs-2\">\r\n");
      out.write("                                                    <div class=\"form-group\">\r\n");
      out.write("                                                        <label for=\"querySubmit\">&nbsp;</label>\r\n");
      out.write("                                                        <button class=\"btn btn-primary form-control\" id=\"querySubmit\">查询</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                            <input type=\"hidden\" id=\"pageCount\" value=\"0\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /.box-header -->\r\n");
      out.write("                        <div class=\"box-body table-responsive\" style=\"overflow: auto\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"form-horizontal\" >\r\n");
      out.write("                                    <div class=\"col-sm-1\">\r\n");
      out.write("                                        <input type=\"button\" onclick=\"batchDeleteItem('student')\" value=\"删除选中项\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-horizontal\" >\r\n");
      out.write("                                    <div class=\"col-sm-1\">\r\n");
      out.write("                                        <input type=\"button\" class=\"form-control\" onclick=\"truncateTable('student')\" value=\"清空数据\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-horizontal\" >\r\n");
      out.write("                                    <label class=\"col-sm-1 control-label\">导出Json文件:</label>\r\n");
      out.write("                                    <div class=\"col-sm-1\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" size=\"2\"  id=\"start\" value=\"0\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-1\">\r\n");
      out.write("                                        <input type=\"text\"  class=\"form-control\" size=\"2\" id=\"limit\" value=\"50\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-sm-1\">\r\n");
      out.write("                                        <input type=\"button\" class=\"form-control\" onclick=\"exportJsonFile()\" value=\"开始导出\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-horizontal\" >\r\n");
      out.write("                                    <label class=\"col-sm-1 control-label\">导入Json文件:</label>\r\n");
      out.write("                                    <div class=\"col-sm-1\">\r\n");
      out.write("                                        <input type=\"file\" id=\"importJsonFile\" class=\"form-control\"\r\n");
      out.write("                                               name=\"myfiles\" onchange=\"importJsonFile('admin/student/import/json')\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <table id=\"example2\" class=\"table table-bordered table-hover dataTable\">\r\n");
      out.write("                                <thead id=\"thead\">\r\n");
      out.write("                                              <tr>\r\n");
      out.write("                                                  <th><input type=\"checkbox\" id=\"checkAll\"></th>\r\n");
      out.write("                                                  <th>序号</th>\r\n");
      out.write("                                                 <th  class=\"sorting\" orderField=\"name\">\r                                                      学生名称\r\n");
      out.write("                                                  </th>\r\n");
      out.write("                                                 <th  class=\"sorting\" orderField=\"class_id\">\r                                                      所属班级\r\n");
      out.write("                                                  </th>\r\n");
      out.write("                                                 <th  class=\"sorting\" orderField=\"sex\">\r                                                      性别\r\n");
      out.write("                                                  </th>\r\n");
      out.write("                                                 <th  class=\"sorting\" orderField=\"admin_user_id\">\r                                                      管理员\r\n");
      out.write("                                                  </th>\r\n");
      out.write("                                                  <th>操作</th>\r\n");
      out.write("                                              </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody id=\"tbody\"></tbody>\r\n");
      out.write("                                <tfoot></tfoot>\r\n");
      out.write("                            </table>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-xs-6\">\r\n");
      out.write("                                    <div class=\"dataTables_info\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-xs-6\">\r\n");
      out.write("                                    <div class=\"dataTables_paginate paging_bootstrap\">\r\n");
      out.write("                                        <ul class=\"pagination\" id=\"pagination\">\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /.box-body -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.box -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- /.content -->\r\n");
      out.write("    </aside>\r\n");
      out.write("    <!-- /.right-side -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<script src=\"assets/admin/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!--https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md-->\r\n");
      out.write("<link href=\"assets/admin/css/typeahead.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"assets/admin/js/bootstrap/typeahead.jquery.min-0.11.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("<script src=\"assets/admin/js/AdminLTE/app.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- magiccoder app-->\r\n");
      out.write("<script src=\"assets/admin/js/page/common_paging.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"assets/admin/js/ajaxfileupload.js\"></script>\r\n");
      out.write("<script charset=\"utf-8\" src=\"assets/admin/app/base.js\"></script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\"\r\n");
      out.write("        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CTX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/admin/js/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("<script src=\"assets/admin/app/list_page.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"assets/admin/app/student/studentPaging.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("    $(function(){\r\n");
      out.write("        //base.js\r\n");
      out.write("            foreignSearch('classes','classIdFirst','','id');\r\n");
      out.write("            foreignSearch('admin_user','adminUserIdFirst','','id');\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/admin/student/../include/left.jsp(18,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/admin/student/../include/left.jsp(18,8) '${userLeftModules}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${userLeftModules}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/admin/student/../include/left.jsp(18,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("ModuleAndCategory");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <li class=\"treeview\">\r\n");
          out.write("                <a href=\"#\">\r\n");
          out.write("                    <i class=\"fa fa-dashboard\"></i> <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ModuleAndCategory.category.moduleCategoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span> <i class=\"fa fa-angle-left pull-right\"></i>\r\n");
          out.write("                </a>\r\n");
          out.write("                <ul class=\"treeview-menu\">\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                </ul>\r\n");
          out.write("            </li>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/jsp/admin/student/../include/left.jsp(24,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("module");
    // /WEB-INF/jsp/admin/student/../include/left.jsp(24,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/admin/student/../include/left.jsp(24,20) '${ModuleAndCategory.moduleList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ModuleAndCategory.moduleList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li><a id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${module.moduleName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${module.moduleUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><i class=\"fa fa-circle-o\"></i> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${module.moduleTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/admin/student/studentList.jsp(68,69) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sex == 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("selected");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/jsp/admin/student/studentList.jsp(72,69) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sex == 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("selected");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
